# Generated by Django 6.1.1 on 2026-09-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='El archivo físico en disco', upload_to='publications_media/')),
                ('caption', models.TextField(blank=True, help_text='Texto o hashtags base', null=True)),
                ('post_type', models.CharField(choices=[('post', 'Post / Feed'), ('reel', 'Reel / Short'), ('story', 'Historia')], default='post', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], max_length=20)),
                ('account_user', models.CharField(max_length=150)),
                ('account_password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PostTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('completed', 'Publicado'), ('failed', 'Error')], default='pending', max_length=20)),
                ('post_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='publications_network.postcontent')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='publications_network.socialaccount')),
            ],
        ),
    ]
